In [3]:
import open3d as o3d
import numpy as np
import sys

sys.path.append('./data/')
from camera import *
from dataloader import *

sys.path.append('./algorithm/')
from measurement import *
from pose import *
from update import *
from prediction import *

from pipeline import *

import matplotlib.pyplot as plt
import time

In [4]:
kf = KinectFusion()
kf.first_frame()
timer = PerfTimer()

while kf.has_next_frame():
    timer.startMeasure("Overall frame")
    kf.next_frame()
    timer.stopMeasure()

KinectFusion pipeline total frame number: 798
Running frame: 0
Running frame: 1
Depth streaming Wall time is 6.761 ms.
Surface Measurement wall time is 7.390 s.
Pose Estimation wall time is 94.157 s.
Pose of this frame is:
[[ 0.99997525 -0.00453627  0.00537727 -0.00121786]
 [ 0.00454862  0.99998704 -0.00228592 -0.00931563]
 [-0.00536683  0.00231032  0.99998293 -0.00622282]
 [ 0.          0.          0.          1.        ]]
As trajectory is: [-0.00122681 -0.00932437 -0.00620797  0.00114907  0.00268604  0.00227124
  0.99999315]
TSDF Update Wall time is 28.980 ms.
Surface Prediction wall time is 8.146 s.
Overall frame wall time is 109.732 s.
Running frame: 2
Depth streaming Wall time is 6.502 ms.
Surface Measurement wall time is 7.051 s.
Pose Estimation wall time is 96.588 s.
Pose of this frame is:
[[ 9.99964346e-01 -5.79744156e-03  6.13972609e-03 -1.92429682e-04]
 [ 5.83023647e-03  9.99968762e-01 -5.33706897e-03 -8.52661631e-03]
 [-6.10859294e-03  5.37267474e-03  9.99966909e-01 -9.60721

KeyboardInterrupt: 